<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AssociationSeeder extends Seeder
{
    /**
     * Asociaciones/Comités extraídos del Reporte de Estructura de Comités.
     */
    public function run(): void
    {
        $associations = [
            [
                'code'             => '150',
                'name'             => 'FRATERNIDAD',
                'address'          => 'Mz.18  Lt.25 y 26 BARRIO I',
                'observation'      => 'Centro Poblado: Fraternidad.',
                'president'        => 'MARIA CRISTINA ZAMORA GALVEZ',
                'resolution_id'    => 40,
                'state_id'         => 1,
                'place_sector_id'  => 25,
                'type_premises_id' => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '160',
                'name'             => 'NUESTRA SEÑORA DE FATIMA',
                'address'          => 'Mz. 9 Lt 8 BARRIO I',
                'observation'      => 'Centro Poblado: Fraternidad.',
                'president'        => 'GUADALUPE TATIANA MARCELO PEREZ',
                'resolution_id'    => 176,
                'state_id'         => 1,
                'place_sector_id'  => 25,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '025',
                'name'             => 'NUEVA ESPERANZA',
                'address'          => 'Mz. Z Lt. 11 AA.HH.',
                'observation'      => 'Centro Poblado: Las Palmeras.',
                'president'        => 'LEYDI YOVANNE BARRAZA VALERIANO',
                'resolution_id'    => 180,
                'state_id'         => 1,
                'place_sector_id'  => 3,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '155',
                'name'             => 'SANTA CATALINA',
                'address'          => 'Mz.06 Lt.23-24 BARRIO I',
                'observation'      => 'Centro Poblado: Fraternidad I .',
                'president'        => 'TANIA FERNANDA LOZANO TACANGA',
                'resolution_id'    => 172,
                'state_id'         => 1,
                'place_sector_id'  => 26,
                'type_premises_id' => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '060',
                'name'             => 'SILOE',
                'address'          => 'Mz.25 Lt.3-A',
                'observation'      => '',
                'president'        => 'SARITA JHUDIT HUACCHA MEDINA',
                'resolution_id'    => 18,
                'state_id'         => 1,
                'place_sector_id'  => 16,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '175',
                'name'             => 'VÍRGENES DEL SOL',
                'address'          => 'Mz.2 Lt.14',
                'observation'      => 'Centro Poblado: Pueblo del Sol. Beneficiarios: 30, Socias: 30.',
                'president'        => 'YRIS LISBETH RODRIGUEZ PAREDES',
                'resolution_id'    => 178,
                'state_id'         => 1,
                'place_sector_id'  => 28,
                'type_premises_id' => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '130',
                'name'             => 'CLEMENTINA PERALTA DE ACUÑA',
                'address'          => 'Mz.16 Lt.5',
                'observation'      => 'Centro Poblado: Los Olivos',
                'president'        => 'RAMOS EDELMIRA MEDINA RODRIGUEZ',
                'resolution_id'    => 141,
                'state_id'         => 1,
                'place_sector_id'  => 22,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '125',
                'name'             => 'CORAZON DE JESÚS N° 08',
                'address'          => 'Mz.7 Lt.32',
                'observation'      => 'Centro Poblado: Los Diamantes',
                'president'        => 'NOEMI GAMBOA PIRGO',
                'resolution_id'    => 95,
                'state_id'         => 1,
                'place_sector_id'  => 21,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '145',
                'name'             => 'LOS NIÑOS DE BELEN',
                'address'          => 'Mz.12 Lt.17',
                'observation'      => 'Centro Poblado: Los Olivos',
                'president'        => 'DEICY MARIBEL CHAVEZ MARIN',
                'resolution_id'    => 189,
                'state_id'         => 1,
                'place_sector_id'  => 22,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '200',
                'name'             => 'MICAELA BASTIDAS',
                'address'          => 'Mac Gregor N° 416',
                'observation'      => 'Centro Poblado: Central.',
                'president'        => 'ROSA BEATRIZ MARREROS DOMINGUEZ',
                'resolution_id'    => 7,
                'state_id'         => 1,
                'place_sector_id'  => 29,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '275',
                'name'             => 'BUEN SOCORRO',
                'address'          => 'Mz M Lt. 25 II Sector',
                'observation'      => 'Centro Poblado: Nuevo Jerusalen',
                'president'        => 'GENOBEBA GOMEZ CUSTODIO DE LOPEZ',
                'resolution_id'    => 114,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '110',
                'name'             => 'CESAR ACUÑA PERALTA',
                'address'          => 'Mz.4 Lt.3',
                'observation'      => 'Centro Poblado: Primavera II.',
                'president'        => 'ELVA DE LA CRUZ MANAYAY',
                'resolution_id'    => 84,
                'state_id'         => 1,
                'place_sector_id'  => 12,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '095',
                'name'             => 'CLEMENTINA ACUÑA DE PERALTA N° 2',
                'address'          => 'Mz.18 Lt.13',
                'observation'      => 'Centro Poblado: Ramiro Priale.',
                'president'        => 'MARIA LIDIA ROJAS TIRADO',
                'resolution_id'    => 170,
                'state_id'         => 1,
                'place_sector_id'  => 18,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '270',
                'name'             => 'CLEMENTINA PERALTA DE ACUÑA',
                'address'          => 'Mz. K Lt. 36 II Sector',
                'observation'      => 'Centro Poblado: Nuevo Jerusalén',
                'president'        => 'OLGA FELICITA GUTIERREZ DE LA CRUZ',
                'resolution_id'    => 154,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '195',
                'name'             => 'ESTRELLA DE LA ESPERANZA',
                'address'          => 'Manuel Cedeño N° 474 BARRIO I',
                'observation'      => 'Centro Poblado: Central',
                'president'        => 'ROSA MARIA VENEGAS TORIBIO',
                'resolution_id'    => 166,
                'state_id'         => 1,
                'place_sector_id'  => 29,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '255',
                'name'             => 'UNIDAS',
                'address'          => 'Mz.29 Lt.02 Barrio 6 Manuel Seoane',
                'observation'      => 'Centro Poblado: Manuel Seoane',
                'president'        => 'FIORELLA GIOVANA LLANOS RAMOS',
                'resolution_id'    => 96,
                'state_id'         => 1,
                'place_sector_id'  => 32,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '220',
                'name'             => 'RIOS DE AGUA VIVA',
                'address'          => 'José Castelli Nº 1413 BARRIO 4',
                'observation'      => 'Centro Poblado: Central. Beneficiarios: 55, Socias: 33.',
                'president'        => 'CARMEN MAURA BENAVIDES VILLANUEVA',
                'resolution_id'    => 98,
                'state_id'         => 1,
                'place_sector_id'  => 29,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
                // aqui nos quedamos
            ],
            [
                'code'             => '370',
                'name'             => 'JEHOVA ES MI PASTOR',
                'address'          => 'Mz.Ñ21 Lt.3',
                'observation'      => 'Centro Poblado: Virgen del Socorro',
                'president'        => 'MARIA FLORECELDA RIVEROS ESCOBAR',
                'resolution_id'    => 88,
                'state_id'         => 1,
                'place_sector_id'  => 39,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '375',
                'name'             => 'JESUS ME GUIA',
                'address'          => 'Mz.N18 Lt.19',
                'observation'      => 'Centro Poblado: Virgen del Socorro.',
                'president'        => 'LOURDES JUDITH VEGA CABRERA',
                'resolution_id'    => 169,
                'state_id'         => 1,
                'place_sector_id'  => 39,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '070',
                'name'             => 'SAN PEDRO',
                'address'          => 'Mz.10 Lt 26',
                'observation'      => 'Centro Poblado: Primavera I',
                'president'        => 'NERY ROCIO SEGURA VALENCIA',
                'resolution_id'    => 121,
                'state_id'         => 1,
                'place_sector_id'  => 11,
                'type_premises_id' => 3,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '380',
                'name'             => 'TANIA SOLEDAD BACA ROMERO',
                'address'          => 'Mz.M18 Lt.03',
                'observation'      => 'Centro Poblado: Virgen del Socorro',
                'president'        => 'ANA CECILIA CAMACHO HOYOS',
                'resolution_id'    => 171,
                'state_id'         => 1,
                'place_sector_id'  => 39,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '050',
                'name'             => 'MADRES TRABAJANDO POR EL GRAN CAMBIO',
                'address'          => 'Mz.I Lt.5',
                'observation'      => 'Centro Poblado: Clementina Peralta Acuña',
                'president'        => 'STEFANY TERESA FLORES MENDEZ',
                'resolution_id'    => 85,
                'state_id'         => 1,
                'place_sector_id'  => 10,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '240',
                'name'             => 'VIRGEN DE LA PUERTA',
                'address'          => 'Tadeo Monagas N° 1694',
                'observation'      => 'Centro Poblado: San Martin',
                'president'        => 'JENNYFER LUCIA LIZA QUEZADA',
                'resolution_id'    => 91,
                'state_id'         => 1,
                'place_sector_id'  => 30,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '265',
                'name'             => 'CLEMENTINA PERALTA DE ACUÑA',
                'address'          => 'Mz.I Lt.38 II Sector',
                'observation'      => 'Centro Poblado: Ampliacion Nuevo Indoamerica',
                'president'        => 'MARIA MARIBEL CARBAJAL TORRES',
                'resolution_id'    => 20,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '040',
                'name'             => 'LAS PALMERAS III',
                'address'          => 'Mz.F1 Lt.13',
                'observation'      => 'Centro Poblado: Las Palmeras',
                'president'        => 'DELSI ELIZABETH PECHE CUSQUIPOMA',
                'resolution_id'    => 86,
                'state_id'         => 1,
                'place_sector_id'  => 3,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '280',
                'name'             => 'VIRGEN DE LA PUERTA',
                'address'          => 'Girardot N° 1543 BARRIO 4',
                'observation'      => 'Centro Poblado: Santa Veronica',
                'president'        => 'NAYSHA ASHLEY VILLANUEVA MARTINEZ',
                'resolution_id'    => 91,
                'state_id'         => 1,
                'place_sector_id'  => 34,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '300',
                'name'             => 'ZOILA DE LA TORRE DE HAYA',
                'address'          => 'Esmeralda N° 350',
                'observation'      => 'Centro Poblado: Santa Veronica.',
                'president'        => 'CYNTHIA LIZBETH LLAURE RODRIGUEZ',
                'resolution_id'    => 100,
                'state_id'         => 1,
                'place_sector_id'  => 34,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '325',
                'name'             => 'ZOILA DE LA TORRE DE HAYA',
                'address'          => 'San Pedro N° 199-A BARRIO 2',
                'observation'      => 'Centro Poblado: Jerusalén.',
                'president'        => 'CARMEN LUZ VICUÑA PINO',
                'resolution_id'    => 168,
                'state_id'         => 1,
                'place_sector_id'  => 35,
                'type_premises_id' => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '340',
                'name'             => 'NTRA.SRA. PERPETUO SOCORRO',
                'address'          => 'Mz. A-15 Lt.08  III Etapa',
                'observation'      => 'Centro Poblado: Manuel Arévalo.',
                'president'        => 'ISIDORA MARIÑAS GARCIA',
                'resolution_id'    => 112,
                'state_id'         => 1,
                'place_sector_id'  => 36,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '360',
                'name'             => 'MANUEL ARÉVALO',
                'address'          => 'Mz. Q Lt.34 Alan Garcia',
                'observation'      => 'Centro Poblado: Alan García.',
                'president'        => 'DIANA ROSA MIGUEL CARUAJULCA',
                'resolution_id'    => 90,
                'state_id'         => 1,
                'place_sector_id'  => 38,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '365',
                'name'             => 'RAMIRO PRIALE PRIALE',
                'address'          => 'Mz.E Lt.02',
                'observation'      => 'Centro Poblado: Alan García.',
                'president'        => 'MARIA ANGELICA GUEVARA PAUCAR',
                'resolution_id'    => 75,
                'state_id'         => 1,
                'place_sector_id'  => 38,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '030',
                'name'             => 'AMIGOS DE JESUS',
                'address'          => 'Mz.E\' Lt.3',
                'observation'      => 'Centro Poblado: Las Palmeras.',
                'president'        => 'OLINDA ANTONIA UCEDA BURGOS',
                'resolution_id'    => 99,
                'state_id'         => 1,
                'place_sector_id'  => 3,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
                //listo
            ],
            [
                'code'             => '082',
                'name'             => 'BODAS DEL CORDERO',
                'address'          => 'Mz. A Lt. 12',
                'observation'      => 'Centro Poblado: Ampliac. Clementina Peralta',
                'president'        => 'EVA JAQUELINE SAAVEDRA MARTINEZ',
                'resolution_id'    => 185,
                'state_id'         => 1,
                'place_sector_id'  => 17,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '036',
                'name'             => 'CORAZÓN DE JESÚS',
                'address'          => 'Mz.A Lt.24',
                'observation'      => 'Centro Poblado: Ampliación Las Palmeras V.',
                'president'        => 'CARMEN PETRONILA LOPEZ PAREDES',
                'resolution_id'    => 67,
                'state_id'         => 1,
                'place_sector_id'  => 8,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
                // por ahora aqui
            ],
            [
                'code'             => '313',
                'name'             => 'DOMITILA CHUNGARA',
                'address'          => 'Canal de Suez N° 1145',
                'observation'      => 'Centro Poblado: Jerusalén.',
                'president'        => 'RUBY NOELIA SANCHEZ GUARNIZ',
                'resolution_id'    => 53,
                'state_id'         => 1,
                'place_sector_id'  => 35,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '273',
                'name'             => 'EDITH SONRISAS DE NIÑOS',
                'address'          => 'Mz.D lT.03 IV Etapa',
                'observation'      => 'Centro Poblado: Nuevo Jerusalén.',
                'president'        => 'DANICA JULLISA MARTINEZ JARA',
                'resolution_id'    => 25,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '378',
                'name'             => 'EL ANGEL',
                'address'          => 'Mz.P17 Lt.2D',
                'observation'      => 'Centro Poblado: VIrgen del Socorro.',
                'president'        => 'DAMIANA LOPEZ GUEVARA',
                'resolution_id'    => 82,
                'state_id'         => 1,
                'place_sector_id'  => 39,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '120',
                'name'             => 'GLORIA VALDERRAMA GARCIA',
                'address'          => 'Mz.5 Lt.21',
                'observation'      => 'Centro Poblado: Los Diamantes.',
                'president'        => 'NAYELI LISBETH CASTILLO MORI',
                'resolution_id'    => 116,
                'state_id'         => 1,
                'place_sector_id'  => 21,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '250',
                'name'             => 'HIJAS DE SION',
                'address'          => 'Mz.A Lt.21 III Sector',
                'observation'      => 'Centro Poblado: Nuevo Jerusalén. ',
                'president'        => 'DAMARIS AXA PALMER VASQUEZ',
                'resolution_id'    => 78,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '093',
                'name'             => 'HILO ROJO',
                'address'          => 'Mz.21 Lt.1',
                'observation'      => 'Centro Poblado: Ramiro Priale.',
                'president'        => 'FLOR ESPERANZA PRETEL MOSTACERO',
                'resolution_id'    => 38,
                'state_id'         => 1,
                'place_sector_id'  => 18,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '105',
                'name'             => 'INDOAMERICA',
                'address'          => 'San Salvador Mz.01 Lt.23-24',
                'observation'      => 'Centro Poblado: Indoamerica. Beneficiarios: 41, Socias: 30.',
                'president'        => 'ERLINDA JHANETH SANDOVAL MINCHOLA',
                'resolution_id'    => 54,
                'state_id'         => 1,
                'place_sector_id'  => 19,
                'type_premises_id' => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '320',
                'name'             => 'JERUSALEN MADRES UNIDAS',
                'address'          => 'Los Cedros N° 678',
                'observation'      => 'Centro Poblado: Jerusalén.',
                'president'        => 'SARITA NOEMI DIAZ OBANDO',
                'resolution_id'    => 129,
                'state_id'         => 1,
                'place_sector_id'  => 35,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '015',
                'name'             => 'JESUS ES MI SALVACION',
                'address'          => 'Mz.B Lt.6 Sector 2',
                'observation'      => 'Centro Poblado: Las Palmeras.',
                'president'        => 'JENNY LISETH ANGULO CHAVEZ',
                'resolution_id'    => 109,
                'state_id'         => 1,
                'place_sector_id'  => 3,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '140',
                'name'             => 'JESUS MI SALVADOR',
                'address'          => 'Mz.10 Lt.18',
                'observation'      => 'Centro Poblado: El Mirador II.',
                'president'        => 'YESENIA MARICIELO SALVADOR LORENZO',
                'resolution_id'    => 23,
                'state_id'         => 1,
                'place_sector_id'  => 1,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '058',
                'name'             => 'JUANA MALAVER DE GARRIDO',
                'address'          => 'Mz.51 Lt.1-A',
                'observation'      => 'Centro Poblado: Wichanzao II.',
                'president'        => 'EMILIA SHITO LOPEZ',
                'resolution_id'    => 19,
                'state_id'         => 1,
                'place_sector_id'  => 15,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '235',
                'name'             => 'LA CARIDAD',
                'address'          => 'José Artigas N° 1628',
                'observation'      => 'Centro Poblado: San Martin.',
                'president'        => 'HAYDEE EMILIA ESLAVA DE AGUIRRE',
                'resolution_id'    => 50,
                'state_id'         => 1,
                'place_sector_id'  => 30,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '068',
                'name'             => 'LA FUERZA DEL PUEBLO',
                'address'          => 'Mz.4 Lt.14 IV Sector',
                'observation'      => 'Centro Poblado: Wichanzao.',
                'president'        => 'YENY MARIANELLA QUEZADA CASTILLO DE AMAYA',
                'resolution_id'    => 130,
                'state_id'         => 1,
                'place_sector_id'  => 14,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '075',
                'name'             => 'LAS DALIAS',
                'address'          => 'Mz.22 Lt.01',
                'observation'      => 'Centro Poblado: Primavera II.',
                'president'        => 'JULISSA MARILIN CHACON VARGAS',
                'resolution_id'    => 194,
                'state_id'         => 1,
                'place_sector_id'  => 12,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '032',
                'name'             => 'LOS ANGELES DE JESUS',
                'address'          => 'Mz.T Lt.10',
                'observation'      => 'Centro Poblado: Ampliación Las Palmeras II.',
                'president'        => 'YOVANA LISBETH VASQUEZ LOYOLA',
                'resolution_id'    => 83,
                'state_id'         => 1,
                'place_sector_id'  => 7,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '246',
                'name'             => 'LOS GERANIOS',
                'address'          => 'Mz.20 Lt.8',
                'observation'      => 'Centro Poblado: Manuel Seoane.',
                'president'        => 'BALTAZAR GOMEZ ANTONILA',
                'resolution_id'    => 39,
                'state_id'         => 1,
                'place_sector_id'  => 32,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '022',
                'name'             => 'MADRE DE CRISTO',
                'address'          => 'Mz.Q Lt.3',
                'observation'      => 'Centro Poblado: Las Palmeras I.',
                'president'        => 'LINARES AQUITUARI ALEYDA GISSELA',
                'resolution_id'    => 110,
                'state_id'         => 1,
                'place_sector_id'  => 5,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '111',
                'name'             => 'MADRE JOSEFINA POTEL',
                'address'          => 'Mz.08 Lt.06',
                'observation'      => 'Centro Poblado: Ampliacion nuevo Indoamérica.',
                'president'        => 'VILLANUEVA CRUZADO CARLA DAMARIS',
                'resolution_id'    => 20,
                'state_id'         => 1,
                'place_sector_id'  => 1,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '045',
                'name'             => 'MADRES TRABAJANDO POR AMPLIACION',
                'address'          => 'Mz.M Lt.04',
                'observation'      => 'Centro Poblado: Clementina Peralta de Acuña.',
                'president'        => 'ZAVALA ASCATE MELISA YENI',
                'resolution_id'    => 123,
                'state_id'         => 1,
                'place_sector_id'  => 10,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '258',
                'name'             => 'MANOS SOLIDARIAS',
                'address'          => 'Mz.C Lt.08 I Sector',
                'observation'      => 'Centro Poblado: Nuevo Jerusalén.',
                'president'        => 'HERAS TASILLA LUZ ELENA',
                'resolution_id'    => 122,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '274',
                'name'             => 'MARTIN NAMAY',
                'address'          => 'Mz.G Lt.12 IV Sector',
                'observation'      => 'Centro Poblado: Nuevo Jerusalen.',
                'president'        => 'MARTINEZ JARA DANICA JULLISA',
                'resolution_id'    => 188,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '034',
                'name'             => 'MUJERES LUCHADORAS',
                'address'          => 'Mz.F Lt.20 Sector I',
                'observation'      => 'Centro Poblado: Las Palmeras. Beneficiarios: 66, Socias: 26.',
                'president'        => 'RIMAYCUNA AGURTO ANALIA DEL CARMEN',
                'resolution_id'    => 144,
                'state_id'         => 1,
                'place_sector_id'  => 3,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '302',
                'name'             => 'MUJERES LUCHANDO POR UN FUTURO MEJOR',
                'address'          => 'Av. Chancay N° 400',
                'observation'      => 'Centro Poblado: Santa Verónica.',
                'president'        => 'JAIME GARCIA ASHLLY OBET',
                'resolution_id'    => 46,
                'state_id'         => 1,
                'place_sector_id'  => 34,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '295',
                'name'             => 'NIÑO MANUELITO',
                'address'          => 'Av. Cahuide N° 230',
                'observation'      => 'Centro Poblado: Santa Verónica.',
                'president'        => 'CASTILLO PAIMA ASTRI KAROLINA',
                'resolution_id'    => 1,
                'state_id'         => 1,
                'place_sector_id'  => 34,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '256',
                'name'             => 'NIÑOS DEL TRIUNFO',
                'address'          => 'Mz.A Lt.25 III Etapa',
                'observation'      => 'Centro Poblado: Los Laureles.',
                'president'        => 'FERNANDEZ ARTEAGA INDIRA JHOSALIN',
                'resolution_id'    => 104,
                'state_id'         => 1,
                'place_sector_id'  => 40,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '170',
                'name'             => 'NUESTRA SEÑORA AUXILIO DE LOS CRISTIANOS',
                'address'          => 'Mz.29 Lt.5',
                'observation'      => 'Centro Poblado: Fraternidad.',
                'president'        => 'ARTEAGA LEON RUBI ESMELDA',
                'resolution_id'    => 162,
                'state_id'         => 1,
                'place_sector_id'  => 25,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '078',
                'name'             => 'NUEVO EDEN',
                'address'          => 'Mz.01 Lt.03 Los Cipreces',
                'observation'      => 'Centro Poblado: Primavera II.',
                'president'        => 'GUTIERREZ CHAVEZ KATHERINE KARINA',
                'resolution_id'    => 57,
                'state_id'         => 1,
                'place_sector_id'  => 12,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '253',
                'name'             => 'NUEVO PARAISO',
                'address'          => 'Mz.A10 Lt.10',
                'observation'      => 'Centro Poblado: Virgen de la Puerta.',
                'president'        => 'CARRANZA MALQUI FIORELA VIRGINIA',
                'resolution_id'    => 113,
                'state_id'         => 1,
                'place_sector_id'  => 33,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '278',
                'name'             => 'NVO. JERUSALEN LA ALEGRIA DE LOS NIÑOS',
                'address'          => 'Mz.Q Lt.22 IV Sector',
                'observation'      => 'Centro Poblado: Nuevo Jerusalén.',
                'president'        => 'FLORIAN CRUZ MONICA GLADIS',
                'resolution_id'    => 133,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '271',
                'name'             => 'ROSITA DE AMOR',
                'address'          => 'Mz.H Lt.36 III Etapa',
                'observation'      => 'Centro Poblado: Nuevo Jerusalén.',
                'president'        => 'ORTIZ TUMBAJULCA ALEXANDRA ANALI',
                'resolution_id'    => 174,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '350',
                'name'             => 'SAN JOSE',
                'address'          => 'Mz.F Lt.40',
                'observation'      => 'Centro Poblado: Villa Hermosa. Beneficiarios: 47, Socias: 24.',
                'president'        => 'GOMEZ ESPINOZA ROSA',
                'resolution_id'    => 175,
                'state_id'         => 1,
                'place_sector_id'  => 37,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '005',
                'name'             => 'SANTA RITA DE CASIA',
                'address'          => 'Mz.7 LT.12',
                'observation'      => 'Centro Poblado: Nuevo Horizonte.',
                'president'        => 'PAREDES ESQUIVEL GIOVANNA ELIZABETH',
                'resolution_id'    => 103,
                'state_id'         => 1,
                'place_sector_id'  => 1,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '230',
                'name'             => 'SANTISIMO SACRAMENTO',
                'address'          => 'Blanco Encalada N° 945',
                'observation'      => 'Centro Poblado: Central. ',
                'president'        => 'YOBANA ISABEL ROBLES SALAS',
                'resolution_id'    => 102,
                'state_id'         => 1,
                'place_sector_id'  => 29,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '268',
                'name'             => 'SEMBRANDO ESPERANZA',
                'address'          => 'Mz.B Lt.15 Sector 3 "B"',
                'observation'      => 'Centro Poblado: Nuevo Jerusalén.',
                'president'        => 'SEGURA CRUZADO FLOR ESTELA',
                'resolution_id'    => 107,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '019',
                'name'             => 'SOL Y ARENA DE LAS PALMERITAS',
                'address'          => 'Ampliación I Mz.B Lt.30 calle Los Laureles',
                'observation'      => 'Centro Poblado: Las Palmeras IV',
                'president'        => 'RABANAL VILLALOBOS DINA BISABE',
                'resolution_id'    => 72,
                'state_id'         => 1,
                'place_sector_id'  => 4,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '388',
                'name'             => 'SUPERMAMAS N° 1',
                'address'          => 'Mz.L13 Lt.2',
                'observation'      => 'Centro Poblado: Virgen del Socorro.',
                'president'        => 'BLAS URQUIZA LIGNE JESUS',
                'resolution_id'    => 147,
                'state_id'         => 1,
                'place_sector_id'  => 39,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '385',
                'name'             => 'TANIA SOLEDAD BACA ROMERO II',
                'address'          => 'Mz.P13 Lt.12D',
                'observation'      => 'Centro Poblado: Virgen del Socorro.',
                'president'        => 'CARRANZA LINARES PATRICIA MARISOL',
                'resolution_id'    => 87,
                'state_id'         => 1,
                'place_sector_id'  => 39,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '118',
                'name'             => 'UNIDAS EN UN SOLO CORAZÓN',
                'address'          => 'Mz.8 Lt.13 Los Rosales',
                'observation'      => 'Centro Poblado: Los Rosales.',
                'president'        => 'REYES RAMOS YARITZA ARACELY',
                'resolution_id'    => 94,
                'state_id'         => 1,
                'place_sector_id'  => 24,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '028',
                'name'             => 'UNIDAS POR LA FAMILIA',
                'address'          => 'Mz.C Lt.08',
                'observation'      => 'Centro Poblado: Ampliac. Las Palmeras.',
                'president'        => 'LAYZA LAVADO ANGELICA ADRIANA',
                'resolution_id'    => 158,
                'state_id'         => 1,
                'place_sector_id'  => 6,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '305',
                'name'             => 'VICTOR RAUL',
                'address'          => 'Marco del Pont N° 2065',
                'observation'      => 'Centro Poblado: Santa Veronica.',
                'president'        => 'ISIQUE VERA ANDREA ROSARIO',
                'resolution_id'    => 167,
                'state_id'         => 1,
                'place_sector_id'  => 34,
                'type_premises_id' => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '090',
                'name'             => 'VIRGEN DE GUADALUPE',
                'address'          => 'MZ.2 LT.12',
                'observation'      => 'Centro Poblado: Ramiro Priale.',
                'president'        => 'SALAZAR SANDOVAL MARIA TEOFILA',
                'resolution_id'    => 92,
                'state_id'         => 1,
                'place_sector_id'  => 18,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '059',
                'name'             => 'VIRGEN DE LA PUERTA',
                'address'          => 'Mz.25 Lt.5A III Sector',
                'observation'      => 'Centro Poblado: Nuevo Jerusalén.',
                'president'        => 'RUBIO DIESTRA LISETT DEL RUBY',
                'resolution_id'    => 56,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '037',
                'name'             => 'WILMER SANCHEZ',
                'address'          => 'Mz.5 Lt.4',
                'observation'      => 'Centro Poblado: María Elena Moyano',
                'president'        => 'SANCHEZ PAREDES ANGELICA ALICIA',
                'resolution_id'    => 21,
                'state_id'         => 1,
                'place_sector_id'  => 9,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
        ];

        DB::table('associations')->insert($associations);
    }
}