<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AssociationSeeder extends Seeder
{
    public function run(): void
    {
        // El comité 256 figura en los padrones de marzo a mayo, pero el Excel
        // de resoluciones no contiene su documento oficial. Se usa un marcador
        // explícito para poder conservar el comité sin atribuirle otra resolución.
        DB::table('resolutions')->updateOrInsert(
            ['document' => 'PENDIENTE-COMITE-256'],
            [
                'date_document' => '2026-03-01 00:00:00',
                'date_start' => '2026-03-01',
                'date_end' => '2026-05-31',
                'file_path' => null,
                'state_id' => DB::table('states')->where('abbreviation', 'VEN')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        );
        $pendingResolution256Id = DB::table('resolutions')
            ->where('document', 'PENDIENTE-COMITE-256')
            ->value('id');

        /**
         * Asociaciones y comités del padrón de beneficiarios.
         * La resolución 1 crea el comité y se guarda en associations.resolution_id.
         * Las resoluciones 2 y 3 se registran después en ResolutionAssociationSeeder.
         */
        $associations = [
            [
                'code'             => '005',
                'name'             => 'SANTA RITA DE CASIA',
                'company_name'     => 'CDM',
                'address'          => 'Mz.7 Lt.12 AA.HH. Nuevo Horizonte',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0921-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 1,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '015',
                'name'             => 'JESÚS ES MI SALVACIÓN',
                'company_name'     => 'CDM',
                'address'          => 'Mz.B Lt.6 Sector 2 - AA.HH. Las Palmeras',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1000-2025')->whereDate('date_start', '2025-09-19')->whereDate('date_end', '2027-09-19')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 2,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '019',
                'name'             => 'SOL Y ARENA DE LAS PALMERITAS',
                'company_name'     => 'CDM',
                'address'          => 'Ampliación I - Mz.B Lt.30 calle Los Laureles - AA.HH. Las Palmeras',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0535-2024')->whereDate('date_start', '2024-06-28')->whereDate('date_end', '2026-06-28')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 2,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '022',
                'name'             => 'MADRE DE CRISTO',
                'company_name'     => 'CDM',
                'address'          => 'Mz.Q Lt.3 AA.HH. Las Palmeras I',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1001-2025')->whereDate('date_start', '2025-09-19')->whereDate('date_end', '2027-09-19')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 2,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '025',
                'name'             => 'NUEVA ESPERANZA',
                'company_name'     => 'CDM',
                'address'          => 'Mz.Z Lt.11 AA.HH. Las Palmeras',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0295-2022')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 2,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '028',
                'name'             => 'UNIDAS POR LA FAMILIA',
                'company_name'     => 'CDM',
                'address'          => 'Mz.C Lt.08 Ampliac. Las Palmeras',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1322-2024')->whereDate('date_start', '2024-12-23')->whereDate('date_end', '2026-12-23')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 2,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '030',
                'name'             => 'AMIGOS DE JESÚS',
                'company_name'     => 'CDM',
                'address'          => 'Mz.E\' Lt.3 AA.HH. Las Palmeras',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0890-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 2,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '032',
                'name'             => 'LOS ANGELES DE JESÚS',
                'company_name'     => 'CDM',
                'address'          => 'Mz.T Lt.10 AA.HH. Ampliación Las Palmeras II',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0871-2020')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 2,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '034',
                'name'             => 'MUJERES LUCHADORAS',
                'company_name'     => 'CDM',
                'address'          => 'Mz.F Lt.20 Sector I - AA.HH. Las Palmeras',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1232-2022')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 2,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '036',
                'name'             => 'CORAZÓN DE JESÚS',
                'company_name'     => 'CDM',
                'address'          => 'Mz.A Lt.24 Amp. Las Palmeras V',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0465-2023')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 2,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '037',
                'name'             => 'WILMER SÁNCHEZ',
                'company_name'     => 'CDM',
                'address'          => 'MZ.5 Lt.4 Maria Elena Moyano',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0146-2023')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 3,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '040',
                'name'             => 'LAS PALMERAS III',
                'company_name'     => 'CDM',
                'address'          => 'Mz.F1 Lt.13 Las Palmeras',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0948-2023')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 2,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '045',
                'name'             => 'MADRES TRABAJANDO POR AMPLIACIÓN',
                'company_name'     => 'CDM',
                'address'          => 'Mz.M Lt.04 AA.HH. Clementina Peralta de Acuña',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1105-2020')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 4,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '050',
                'name'             => 'MADRES TRABAJANDO POR EL GRAN CAMBIO',
                'company_name'     => 'CDM',
                'address'          => 'MZ. I Lt.5 AA.HH. Clementina Peralta de Acuña',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0890-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 4,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '058',
                'name'             => 'JUANA MALAVER DE GARRIDO',
                'company_name'     => 'CDM',
                'address'          => 'Mz.51 Lt.1-A Wichanzao II',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0058-2020')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 5,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '059',
                'name'             => 'VIRGEN DE LA PUERTA',
                'company_name'     => 'CDM',
                'address'          => 'Mz.25 Lt.5A III Sector - AA.HH. Nuevo Jerusalén',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0316-2025')->whereDate('date_start', '2025-03-27')->whereDate('date_end', '2027-03-27')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 19,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '060',
                'name'             => 'SILOÉ',
                'company_name'     => 'CDM',
                'address'          => 'Mz.25 Lt.3-A Wichanzao III',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0176-2022')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 5,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '068',
                'name'             => 'LA FUERZA DEL PUEBLO',
                'company_name'     => 'CDM',
                'address'          => 'Mz.4 Lt.14 IV Sector - Wichanzao',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1165-2023')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 5,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '070',
                'name'             => 'SAN PEDRO',
                'company_name'     => 'CDM',
                'address'          => 'Mz.10 Lt.26 AA.HH. Primavera I',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1101-2020')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 6,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '075',
                'name'             => 'LAS DALIAS',
                'company_name'     => 'CDM',
                'address'          => 'Mz.21 Lt.01 AA.HH. Primavera II',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1770-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 6,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '078',
                'name'             => 'NUEVO EDÉN',
                'company_name'     => 'CDM',
                'address'          => 'Mz.01 Lt.03 Los Cipreces - AA.HH. Primavera II',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0444-2022')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 6,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '080',
                'name'             => 'AMIGAS UNIDAS',
                'company_name'     => 'CDM',
                'address'          => 'Mz.E Lt.21 Primavera III',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0703-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 6,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '082',
                'name'             => 'BODAS DEL CORDERO',
                'company_name'     => 'CDM',
                'address'          => 'Mz.A Lt.12 AA.HH. Ampliación Clementina Peralta de A.',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1704-2023')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 4,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '090',
                'name'             => 'VIRGEN DE GUADALUPE',
                'company_name'     => 'CDM',
                'address'          => 'Mz.2 Lt.12 Ramiro Priale',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0790-2020')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 7,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '093',
                'name'             => 'HILO ROJO',
                'company_name'     => 'CDM',
                'address'          => 'Mz.21 Lt.1 Ramiro Priale',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0206-2023')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 7,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '095',
                'name'             => 'CLEMENTINA ACUÑA DE PERALTA N° 2',
                'company_name'     => 'CDM',
                'address'          => 'Mz.18 Lt.13 Ramiro Priale',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1771-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 7,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '105',
                'name'             => 'INDOAMERICA',
                'company_name'     => 'CDM',
                'address'          => 'San Salvador Mz.01 Lt.23-24 Sector Indoamerica',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0310-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 8,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '110',
                'name'             => 'CÉSAR ACUÑA PERALTA',
                'company_name'     => 'CDM',
                'address'          => 'Mz. 4 Lt.3 AA.HH. Ampliación Primavera II',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0688-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 6,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '111',
                'name'             => 'MADRE JOSEFINA POTEL',
                'company_name'     => 'CDM',
                'address'          => 'Mz.08 Lt.06 Sector Ampliación Nuevo Indoamerica',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0057-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 8,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '118',
                'name'             => 'UNIDAS EN UN SOLO CORAZÓN',
                'company_name'     => 'CDM',
                'address'          => 'Mz.8 Lt.13 Sector Los Rosales',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0795-2024')->whereDate('date_start', '2024-08-28')->whereDate('date_end', '2026-08-28')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 9,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '120',
                'name'             => 'GLORIA VALDERRAMA GARCIA',
                'company_name'     => 'CDM',
                'address'          => 'MZ.5 Lt.21 Los Diamantes',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1056-2022')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 10,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '125',
                'name'             => 'CORAZÓN DE JESÚS N° 08',
                'company_name'     => 'CDM',
                'address'          => 'Mz.7 Lt.32 Los Diamantes',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0800-2020')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 10,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '130',
                'name'             => 'CLEMENTINA PERALTA DE A. (Los Olivos)',
                'company_name'     => 'CDM',
                'address'          => 'Mz.16 Lt.5 Los Olivos',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1897-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 11,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '140',
                'name'             => 'JESÚS MI SALVADOR',
                'company_name'     => 'CDM',
                'address'          => 'Mz.10 Lt.18 Sector El Mirador II',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0451-2022')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 12,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '145',
                'name'             => 'LOS NIÑOS DE BELÉN',
                'company_name'     => 'CDM',
                'address'          => 'Mz.12 Lt.17 Los Olivos',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1336-2022')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 11,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '150',
                'name'             => 'FRATERNIDAD',
                'company_name'     => 'CDM',
                'address'          => 'Mz.18 Lt.25 y 26 Barrio I - Fraternidad',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0216-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 13,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '155',
                'name'             => 'SANTA CATALINA',
                'company_name'     => 'CDM',
                'address'          => 'Mz.06 Lt.23-24 Barrio I - Fraternidad',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1747-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 13,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '160',
                'name'             => 'NUESTRA SEÑORA DE FÁTIMA',
                'company_name'     => 'CDM',
                'address'          => 'Mz.9 Lt.8 Barrio I - Sector Fraternidad',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0215-2022')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 13,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '170',
                'name'             => 'NSTRA. SRA. AUXILIO DE LOS CRISTIANOS',
                'company_name'     => 'CDM',
                'address'          => 'Mz.29 Lt.5 Fraternidad',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1735-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 13,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '175',
                'name'             => 'VIRGENES DEL SOL',
                'company_name'     => 'CDM',
                'address'          => 'Mz.2 LT.14 Pueblo el Sol',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1775-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 14,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '195',
                'name'             => 'ESTRELLA DE LA ESPERANZA',
                'company_name'     => 'CDM',
                'address'          => 'Manuel Cedeño N° 474 Barrio I',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1355-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 15,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '200',
                'name'             => 'MICAELA BASTIDAS',
                'company_name'     => 'CDM',
                'address'          => 'Mac Gregor N° 416',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0159-2022')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 16,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '220',
                'name'             => 'RIOS DE AGUA VIVA',
                'company_name'     => 'CDM',
                'address'          => 'José Castelli N° 1413 Barrio 4',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0683-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 17,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '230',
                'name'             => 'SANTÍSIMO SACRAMENTO',
                'company_name'     => 'CDM',
                'address'          => 'Blanco Encalada N° 945 - Sector Central',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0520-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 16,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '235',
                'name'             => 'LA CARIDAD',
                'company_name'     => 'CDM',
                'address'          => 'José Artigas N° 1628 Sector San Martin',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0283-2025')->whereDate('date_start', '2025-03-17')->whereDate('date_end', '2027-03-17')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 18,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '240',
                'name'             => 'VIRGEN DE LA PUERTA (San Martin)',
                'company_name'     => 'CDM',
                'address'          => 'Tadeo Monagas N° 1694 Sector San Martin',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0158-2022')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 18,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '246',
                'name'             => 'LOS GERANIOS',
                'company_name'     => 'CDM',
                'address'          => 'Mz.20 Lt.8 Manuel Seoane',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0207-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 20,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '250',
                'name'             => 'HIJAS DE SIÓN',
                'company_name'     => 'CDM',
                'address'          => 'Mz.A Lt.21 III Sector - AA.HH. Nuevo Jerusalén',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0587-2020')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 19,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '253',
                'name'             => 'NUEVO PARAISO',
                'company_name'     => 'CDM',
                'address'          => 'Mz.A10 Lt.10 Sector Virgen de la Puerta',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1048-2020')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 21,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '255',
                'name'             => 'UNIDAS',
                'company_name'     => 'CDM',
                'address'          => 'Mz.29 Lt.02 Barrio 6 Manuel Seoane',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0801-2020')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 20,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '256',
                'name'             => 'NIÑOS DEL TRIUNFO',
                'company_name'     => 'CDM',
                'address'          => 'Mz.A Lt.25 III Etapa - Los Laureles',
                'observation'      => 'Figura en los padrones de marzo a mayo de 2026; resolución oficial pendiente.',
                'phone'            => null,
                'resolution_id'    => $pendingResolution256Id,
                'state_id'         => DB::table('states')->where('abbreviation', 'VEN')->value('id'),
                'place_sector_id'  => 19,
                'type_premises_id' => 2,
            ],
            [
                'code'             => '258',
                'name'             => 'MANOS SOLIDARIAS',
                'company_name'     => 'CDM',
                'address'          => 'MZ.C Lt.08 I Sector - AA.HH. Nuevo Jerusalén',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1104-2020')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 19,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '265',
                'name'             => 'CLEMENTINA PERALTA DE ACUÑA',
                'company_name'     => 'CDM',
                'address'          => 'Mz.I Lt.38 II Sector - AA.HH. Nuevo Jerusalén',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0120-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 19,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '268',
                'name'             => 'SEMBRANDO ESPERANZA',
                'company_name'     => 'CDM',
                'address'          => 'Mz-B Lt.15 Sector 3 "B" - AA.HH. Nuevo Jerusalén',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0993-2025')->whereDate('date_start', '2025-09-17')->whereDate('date_end', '2027-09-17')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 19,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '270',
                'name'             => 'CLEMENTINA PERALTA DE ACUÑA',
                'company_name'     => 'CDM',
                'address'          => 'Mz.K Lt.36 II Sector - AA.HH. Nuevo Jerusalén',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1259-2020')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 19,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '271',
                'name'             => 'ROSITA DE AMOR',
                'company_name'     => 'CDM',
                'address'          => 'Mz.H Lt.36 III Etapa - AA.HH. Nuevo Jerusalén',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1443-2023')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 19,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '273',
                'name'             => 'EDITH SONRISAS DE NIÑOS',
                'company_name'     => 'CDM',
                'address'          => 'Mz.D Lt.03 IV Etapa-Nvo.Jerusalén',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0152-2023')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 19,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '274',
                'name'             => 'MARTIN NAMAY',
                'company_name'     => 'CDM',
                'address'          => 'Mz.G Lt.12 IV Sector-Nvo. Jerusalén',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1714-2022')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 19,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '275',
                'name'             => 'BUEN SOCORRO',
                'company_name'     => 'CDM',
                'address'          => 'Mz.M Lt.25 II Sector - Nvo. Jerusalén',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1050-2020')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 19,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '278',
                'name'             => 'NVO. JERUSALEN LA ALEGRIA DE LOS NIÑOS',
                'company_name'     => 'CDM',
                'address'          => 'Mz.Q Lt.22 IV Sector - AA.HH. Nuevo Jerusalén',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1173-2024')->whereDate('date_start', '2024-11-22')->whereDate('date_end', '2026-11-22')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 19,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '280',
                'name'             => 'VIRGEN DE LA PUERTA',
                'company_name'     => 'CDM',
                'address'          => 'Girardot N° 1543 - Sector Santa Verónica',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0785-2020')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 22,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '295',
                'name'             => 'NIÑO MANUELITO',
                'company_name'     => 'CDM',
                'address'          => 'Av. Cahuide N° 230 - Sector Santa Verónica',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0156-2022')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 22,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '300',
                'name'             => 'ZOILA DE LA TORRE DE HAYA',
                'company_name'     => 'CDM',
                'address'          => 'Calle Esmeralda N° 350 - Sector Santa Verónica',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0891-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 22,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '302',
                'name'             => 'MUJERES LUCHANDO POR UN FUTURO MEJOR',
                'company_name'     => 'CDM',
                'address'          => 'Av. Chancay N° 400 - Sector Verónica',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0252-2023')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 22,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '305',
                'name'             => 'VICTOR RAÚL',
                'company_name'     => 'CDM',
                'address'          => 'Marco del Pont N° 2065 - Sector Santa Verónica',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1595-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 22,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '313',
                'name'             => 'DOMITILA CHUNGARA',
                'company_name'     => 'CDM',
                'address'          => 'Canal de Suez N° 1145 - Sector Jerusalén',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0146-2023')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 23,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '320',
                'name'             => 'JERUSALÉN MADRES UNIDAS',
                'company_name'     => 'CDM',
                'address'          => 'Calle Los Cedros N° 678 - Sector Jerusalén',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1168-2023')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 23,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '325',
                'name'             => 'ZOILA DE LA TORRE DE HAYA',
                'company_name'     => 'CDM',
                'address'          => 'Calle San Pedro N° 199-A - Sector Jerusalén',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1734-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 23,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '340',
                'name'             => 'NSTRA. SRA. DEL PERPETUO SOCORRO',
                'company_name'     => 'CDM',
                'address'          => 'Mz.A-15 Lt.08 III Etapa - Manuel Arévalo',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1019-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 24,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '350',
                'name'             => 'SAN JOSÉ',
                'company_name'     => 'CDM',
                'address'          => 'Mz.F Lt.40 Villa Hermosa',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1812-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 25,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '360',
                'name'             => 'MANUEL ARÉVALO',
                'company_name'     => 'CDM',
                'address'          => 'Mz.Q Lt.34 Alan Garcia',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0774-2020')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 26,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '365',
                'name'             => 'RAMIRO PRIALE',
                'company_name'     => 'CDM',
                'address'          => 'Mz.E Lt.02 Alan Garcia',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0643-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 26,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '370',
                'name'             => 'JEHOVÁ ES MI PASTOR',
                'company_name'     => 'CDM',
                'address'          => 'Mz.Ñ21 Lt.3 Virgen del Socorro',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0746-2020')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 27,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '375',
                'name'             => 'JESÚS ME GUIA',
                'company_name'     => 'CDM',
                'address'          => 'Mz.N18 Lt.19 Virgen del Socorro',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1733-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 27,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '378',
                'name'             => 'EL ANGEL',
                'company_name'     => 'CDM',
                'address'          => 'Mz.P17Lt.2D Virgen del Socorro',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0830-2024')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 27,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '380',
                'name'             => 'TANIA SOLEDAD BACA ROMERO',
                'company_name'     => 'CDM',
                'address'          => 'Mz.M18 Lt.03 Virgen del Socorro',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1704-2021')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 27,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '385',
                'name'             => 'TANIA SOLEDAD BACA ROMERO II',
                'company_name'     => 'CDM',
                'address'          => 'MZ.P13 Lt.12B Virgen del Socorro',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '0744-2020')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 27,
                'type_premises_id' => 1,
            ],
            [
                'code'             => '388',
                'name'             => 'SUPERMAMÁS N° 1',
                'company_name'     => 'CDM',
                'address'          => 'Mz.L13 Lt.2 Virgen del Socorro',
                'observation'      => null,
                'phone'            => null,
                'resolution_id'    => DB::table('resolutions')->where('document', '1236-2025')->whereDate('date_start', '2025-11-20')->whereDate('date_end', '2027-11-20')->value('id'),
                'state_id'         => 1,
                'place_sector_id'  => 27,
                'type_premises_id' => 1,
            ],
        ];

        foreach ($associations as $a) {
            // Al reejecutar el seeder sobre una base ya migrada, algunas
            // resoluciones históricas tienen fechas completadas y la búsqueda
            // original puede no encontrarlas. En ese caso se conserva la
            // resolución primaria ya ligada al comité.
            if (!$a['resolution_id']) {
                $a['resolution_id'] = DB::table('associations')
                    ->where('code', $a['code'])
                    ->value('resolution_id');
            }

            if (!$a['resolution_id']) {
                throw new \RuntimeException("No se pudo resolver la resolución del comité {$a['code']}.");
            }

            DB::table('associations')->updateOrInsert(
                ['code' => $a['code']],
                array_merge($a, ['created_at' => now(), 'updated_at' => now()])
            );
        }

    }
}
