<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AssociationSeeder extends Seeder
{
    /**
     * Asociaciones/Comités extraídos del Reporte de Estructura de Comités.
     */
    public function run(): void
    {
        // company_name : 'CDM', 'CVL', 'OSB'
        $associations = [
            [
                'code'             => '150',
                'name'             => 'FRATERNIDAD',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.18  Lt.25 y 26 BARRIO I',
                'observation'      => 'Centro Poblado: Fraternidad.',
                #'president'        => 'MARIA CRISTINA ZAMORA GALVEZ',
                'resolution_id'    => 40,
                'state_id'         => 1,
                'place_sector_id'  => 25,
                'type_premises_id' => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '160',
                'name'             => 'NUESTRA SEÑORA DE FATIMA',
                'company_name'     => 'CVL', 
                'address'          => 'Mz. 9 Lt 8 BARRIO I',
                'observation'      => 'Centro Poblado: Fraternidad.',
                #'president'        => 'GUADALUPE TATIANA MARCELO PEREZ',
                'resolution_id'    => 176,
                'state_id'         => 1,
                'place_sector_id'  => 25,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '025',
                'name'             => 'NUEVA ESPERANZA',
                'company_name'     => 'CDM', 
                'address'          => 'Mz. Z Lt. 11 AA.HH.',
                'observation'      => 'Centro Poblado: Las Palmeras.',
                #'president'        => 'LEYDI YOVANNE BARRAZA VALERIANO',
                'resolution_id'    => 180,
                'state_id'         => 1,
                'place_sector_id'  => 3,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '155',
                'name'             => 'SANTA CATALINA',
                'company_name'     => 'OSB', 
                'address'          => 'Mz.06 Lt.23-24 BARRIO I',
                'observation'      => 'Centro Poblado: Fraternidad I .',
                #'president'        => 'TANIA FERNANDA LOZANO TACANGA',
                'resolution_id'    => 172,
                'state_id'         => 1,
                'place_sector_id'  => 26,
                'type_premises_id' => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '060',
                'name'             => 'SILOE',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.25 Lt.3-A',
                'observation'      => 'Centro Poblado: Wichanzao III',
                #'president'        => 'SARITA JHUDIT HUACCHA MEDINA',
                'resolution_id'    => 18,
                'state_id'         => 1,
                'place_sector_id'  => 16,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '175',
                'name'             => 'VÍRGENES DEL SOL',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.2 Lt.14',
                'observation'      => 'Centro Poblado: Pueblo del Sol.',
                #'president'        => 'YRIS LISBETH RODRIGUEZ PAREDES',
                'resolution_id'    => 178,
                'state_id'         => 1,
                'place_sector_id'  => 28,
                'type_premises_id' => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '130',
                'name'             => 'CLEMENTINA PERALTA DE ACUÑA',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.16 Lt.5',
                'observation'      => 'Centro Poblado: Los Olivos',
                #'president'        => 'RAMOS EDELMIRA MEDINA RODRIGUEZ',
                'resolution_id'    => 141,
                'state_id'         => 1,
                'place_sector_id'  => 22,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '125',
                'name'             => 'CORAZON DE JESÚS N° 08',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.7 Lt.32',
                'observation'      => 'Centro Poblado: Los Diamantes',
                #'president'        => 'NOEMI GAMBOA PIRGO',
                'resolution_id'    => 95,
                'state_id'         => 1,
                'place_sector_id'  => 21,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '145',
                'name'             => 'LOS NIÑOS DE BELEN',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.12 Lt.17',
                'observation'      => 'Centro Poblado: Los Olivos',
                #'president'        => 'DEICY MARIBEL CHAVEZ MARIN',
                'resolution_id'    => 189,
                'state_id'         => 1,
                'place_sector_id'  => 22,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '200',
                'name'             => 'MICAELA BASTIDAS',
                'company_name'     => 'CDM', 
                'address'          => 'Mac Gregor N° 416 Barrio 5',
                'observation'      => 'Centro Poblado: Central.',
                #'president'        => 'ROSA BEATRIZ MARREROS DOMINGUEZ',
                'resolution_id'    => 7,
                'state_id'         => 1,
                'place_sector_id'  => 29,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '275',
                'name'             => 'BUEN SOCORRO',
                'company_name'     => 'CDM', 
                'address'          => 'Mz M Lt. 25 II Sector',
                'observation'      => 'Centro Poblado: Nuevo Jerusalen',
                #'president'        => 'GENOBEBA GOMEZ CUSTODIO DE LOPEZ',
                'resolution_id'    => 114,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '110',
                'name'             => 'CESAR ACUÑA PERALTA',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.4 Lt.3 AA.HH.',
                'observation'      => 'Centro Poblado: Primavera II.',
                #'president'        => 'ELVA DE LA CRUZ MANAYAY',
                'resolution_id'    => 84,
                'state_id'         => 1,
                'place_sector_id'  => 12,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '095',
                'name'             => 'CLEMENTINA ACUÑA DE PERALTA N° 2',
                'company_name'     => 'OSB', 
                'address'          => 'Mz.18 Lt.13',
                'observation'      => 'Centro Poblado: Ramiro Priale.',
                #'president'        => 'MARIA LIDIA ROJAS TIRADO',
                'resolution_id'    => 170,
                'state_id'         => 1,
                'place_sector_id'  => 18,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '270',
                'name'             => 'CLEMENTINA PERALTA DE ACUÑA',
                'company_name'     => 'CDM', 
                'address'          => 'Mz. K Lt. 36 II Sector',
                'observation'      => 'Centro Poblado: Nuevo Jerusalén',
                #'president'        => 'OLGA FELICITA GUTIERREZ DE LA CRUZ',
                'resolution_id'    => 154,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '195',
                'name'             => 'ESTRELLA DE LA ESPERANZA',
                'company_name'     => 'CDM', 
                'address'          => 'Manuel Cedeño N° 474 BARRIO I',
                'observation'      => 'Centro Poblado: Central',
                #'president'        => 'ROSA MARIA VENEGAS TORIBIO',
                'resolution_id'    => 166,
                'state_id'         => 1,
                'place_sector_id'  => 29,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '255',
                'name'             => 'UNIDAS',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.29 Lt.02 Barrio 6',
                'observation'      => 'Centro Poblado: Manuel Seoane',
                #'president'        => 'FIORELLA GIOVANA LLANOS RAMOS',
                'resolution_id'    => 96,
                'state_id'         => 1,
                'place_sector_id'  => 32,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '220',
                'name'             => 'RIOS DE AGUA VIVA',
                'company_name'     => 'OSB', 
                'address'          => 'José Castelli N° 1413 BARRIO 4',
                'observation'      => 'Centro Poblado: Central.',
                #'president'        => 'CARMEN MAURA BENAVIDES VILLANUEVA',
                'resolution_id'    => 98,
                'state_id'         => 1,
                'place_sector_id'  => 29,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '370',
                'name'             => 'JEHOVA ES MI PASTOR',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.Ñ21 Lt.3',
                'observation'      => 'Centro Poblado: Virgen del Socorro',
                #'president'        => 'MARIA FLORECELDA RIVEROS ESCOBAR',
                'resolution_id'    => 88,
                'state_id'         => 1,
                'place_sector_id'  => 39,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '375',
                'name'             => 'JESUS ME GUIA',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.N18 Lt.19',
                'observation'      => 'Centro Poblado: Virgen del Socorro.',
                #'president'        => 'LOURDES JUDITH VEGA CABRERA',
                'resolution_id'    => 169,
                'state_id'         => 1,
                'place_sector_id'  => 39,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '070',
                'name'             => 'SAN PEDRO',
                'company_name'     => 'OSB', 
                'address'          => 'Mz.10 Lt 26',
                'observation'      => 'Centro Poblado: Primavera I',
                #'president'        => 'NERY ROCIO SEGURA VALENCIA',
                'resolution_id'    => 121,
                'state_id'         => 1,
                'place_sector_id'  => 11,
                'type_premises_id' => 3,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '380',
                'name'             => 'TANIA SOLEDAD BACA ROMERO',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.M18 Lt.03',
                'observation'      => 'Centro Poblado: Virgen del Socorro',
                #'president'        => 'ANA CECILIA CAMACHO HOYOS',
                'resolution_id'    => 171,
                'state_id'         => 1,
                'place_sector_id'  => 39,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '050',
                'name'             => 'MADRES TRABAJANDO POR EL GRAN CAMBIO',
                'company_name'     => 'CVL', 
                'address'          => 'Mz.I Lt.5 AA.HH.',
                'observation'      => 'Centro Poblado: Clementina Peralta Acuña',
                #'president'        => 'STEFANY TERESA FLORES MENDEZ',
                'resolution_id'    => 85,
                'state_id'         => 1,
                'place_sector_id'  => 10,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '240',
                'name'             => 'VIRGEN DE LA PUERTA',
                'company_name'     => 'CDM', 
                'address'          => 'Tadeo Monagas N° 1694',
                'observation'      => 'Centro Poblado: San Martin',
                #'president'        => 'JENNYFER LUCIA LIZA QUEZADA',
                'resolution_id'    => 177,
                'state_id'         => 1,
                'place_sector_id'  => 30,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '265',
                'name'             => 'CLEMENTINA PERALTA DE ACUÑA',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.I Lt.38 II Sector AA.HH.',
                'observation'      => 'Centro Poblado: Nuevo Jerusalen',
                #'president'        => 'MARIA MARIBEL CARBAJAL TORRES',
                'resolution_id'    => 20,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '040',
                'name'             => 'LAS PALMERAS III',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.F1 Lt.13',
                'observation'      => 'Centro Poblado: Las Palmeras',
                #'president'        => 'DELSI ELIZABETH PECHE CUSQUIPOMA',
                'resolution_id'    => 86,
                'state_id'         => 1,
                'place_sector_id'  => 3,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '280',
                'name'             => 'VIRGEN DE LA PUERTA',
                'company_name'     => 'CDM', 
                'address'          => 'Girardot N° 1543 BARRIO 4',
                'observation'      => 'Centro Poblado: Santa Veronica',
                #'president'        => 'NAYSHA ASHLEY VILLANUEVA MARTINEZ',
                'resolution_id'    => 91,
                'state_id'         => 1,
                'place_sector_id'  => 34,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '300',
                'name'             => 'ZOILA DE LA TORRE DE HAYA',
                'company_name'     => 'CDM', 
                'address'          => 'Esmeralda N° 350',
                'observation'      => 'Centro Poblado: Santa Veronica.',
                #'president'        => 'CYNTHIA LIZBETH LLAURE RODRIGUEZ',
                'resolution_id'    => 100,
                'state_id'         => 1,
                'place_sector_id'  => 34,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '325',
                'name'             => 'ZOILA DE LA TORRE DE HAYA',
                'company_name'     => 'CDM', 
                'address'          => 'San Pedro N° 199-A BARRIO 2',
                'observation'      => 'Centro Poblado: Jerusalén.',
                #'president'        => 'CARMEN LUZ VICUÑA PINO',
                'resolution_id'    => 168,
                'state_id'         => 1,
                'place_sector_id'  => 35,
                'type_premises_id' => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '340',
                'name'             => 'NTRA.SRA. PERPETUO SOCORRO',
                'company_name'     => 'CDM', 
                'address'          => 'Mz. A-15 Lt.08  III Etapa',
                'observation'      => 'Centro Poblado: Manuel Arévalo.',
                #'president'        => 'ISIDORA MARIÑAS GARCIA',
                'resolution_id'    => 112,
                'state_id'         => 1,
                'place_sector_id'  => 36,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '360',
                'name'             => 'MANUEL ARÉVALO',
                'company_name'     => 'CDM', 
                'address'          => 'Mz. Q Lt.34',
                'observation'      => 'Centro Poblado: Alan García.',
                #'president'        => 'DIANA ROSA MIGUEL CARUAJULCA',
                'resolution_id'    => 90,
                'state_id'         => 1,
                'place_sector_id'  => 38,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '365',
                'name'             => 'RAMIRO PRIALE PRIALE',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.E Lt.02',
                'observation'      => 'Centro Poblado: Alan García.',
                #'president'        => 'MARIA ANGELICA GUEVARA PAUCAR',
                'resolution_id'    => 75,
                'state_id'         => 1,
                'place_sector_id'  => 38,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '030',
                'name'             => 'AMIGOS DE JESUS',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.E Lt.3 AA.HH.',
                'observation'      => 'Centro Poblado: Las Palmeras.',
                #'president'        => 'OLINDA ANTONIA UCEDA BURGOS',
                'resolution_id'    => 99,
                'state_id'         => 1,
                'place_sector_id'  => 3,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '082',
                'name'             => 'BODAS DEL CORDERO',
                'company_name'     => 'CDM', 
                'address'          => 'Mz. A Lt. 12',
                'observation'      => 'Centro Poblado: Ampliación Clementina Peralta de Acuña',
                #'president'        => 'EVA JAQUELINE SAAVEDRA MARTINEZ',
                'resolution_id'    => 185,
                'state_id'         => 1,
                'place_sector_id'  => 17,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '036',
                'name'             => 'CORAZÓN DE JESÚS',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.A Lt.24',
                'observation'      => 'Centro Poblado: Ampliación Las Palmeras V.',
                #'president'        => 'CARMEN PETRONILA LOPEZ PAREDES',
                'resolution_id'    => 67,
                'state_id'         => 1,
                'place_sector_id'  => 8,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '313',
                'name'             => 'DOMITILA CHUNGARA',
                'company_name'     => 'CDM', 
                'address'          => 'Canal de Suez N° 1145',
                'observation'      => 'Centro Poblado: Jerusalén.',
                #'president'        => 'RUBY NOELIA SANCHEZ GUARNIZ',
                'resolution_id'    => 53,
                'state_id'         => 1,
                'place_sector_id'  => 35,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '273',
                'name'             => 'EDITH SONRISAS DE NIÑOS',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.D lT.03 IV Etapa',
                'observation'      => 'Centro Poblado: Nuevo Jerusalén.',
                #'president'        => 'MARIA LUZ ELENA LAYZA MARIN',
                'resolution_id'    => 25,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '378',
                'name'             => 'EL ANGEL',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.P17 Lt.2D',
                'observation'      => 'Centro Poblado: VIrgen del Socorro.',
                #'president'        => 'DAMIANA LOPEZ GUEVARA',
                'resolution_id'    => 82,
                'state_id'         => 1,
                'place_sector_id'  => 39,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '120',
                'name'             => 'GLORIA VALDERRAMA GARCIA',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.5 Lt.21',
                'observation'      => 'Centro Poblado: Los Diamantes.',
                #'president'        => 'NAYELI LISBETH CASTILLO MORI',
                'resolution_id'    => 116,
                'state_id'         => 1,
                'place_sector_id'  => 21,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '250',
                'name'             => 'HIJAS DE SION',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.A Lt.21 III Sector AA.HH.',
                'observation'      => 'Centro Poblado: Nuevo Jerusalén. ',
                #'president'        => 'DAMARIS AXA PALMER VASQUEZ',
                'resolution_id'    => 78,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '093',
                'name'             => 'HILO ROJO',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.21 Lt.1',
                'observation'      => 'Centro Poblado: Ramiro Priale.',
                #'president'        => 'FLOR ESPERANZA PRETEL MOSTACERO',
                'resolution_id'    => 38,
                'state_id'         => 1,
                'place_sector_id'  => 18,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '105',
                'name'             => 'INDOAMERICA',
                'company_name'     => 'CDM', 
                'address'          => 'San Salvador Mz.01 Lt.23-24',
                'observation'      => 'Centro Poblado: Indoamerica.',
                #'president'        => 'ERLINDA JHANETH SANDOVAL MINCHOLA',
                'resolution_id'    => 54,
                'state_id'         => 1,
                'place_sector_id'  => 19,
                'type_premises_id' => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '320',
                'name'             => 'JERUSALEN MADRES UNIDAS',
                'company_name'     => 'CDM', 
                'address'          => 'Los Cedros N° 678',
                'observation'      => 'Centro Poblado: Jerusalén.',
                #'president'        => 'SARITA NOEMI DIAZ OBANDO',
                'resolution_id'    => 129,
                'state_id'         => 1,
                'place_sector_id'  => 35,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '015',
                'name'             => 'JESUS ES MI SALVACION',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.B Lt.6 Sector  AA.HH.',
                'observation'      => 'Centro Poblado: Las Palmeras.',
                #'president'        => 'JENNY LISETH ANGULO CHAVEZ',
                'resolution_id'    => 109,
                'state_id'         => 1,
                'place_sector_id'  => 3,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '140',
                'name'             => 'JESUS MI SALVADOR',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.10 Lt.18',
                'observation'      => 'Centro Poblado: El Mirador II.',
                #'president'        => 'YESENIA MARICIELO SALVADOR LORENZO',
                'resolution_id'    => 37,
                'state_id'         => 1,
                'place_sector_id'  => 23,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '058',
                'name'             => 'JUANA MALAVER DE GARRIDO',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.51 Lt.1-A',
                'observation'      => 'Centro Poblado: Wichanzao II.',
                #'president'        => 'EMILIA SHITO LOPEZ',
                'resolution_id'    => 19,
                'state_id'         => 1,
                'place_sector_id'  => 15,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '235',
                'name'             => 'LA CARIDAD',
                'company_name'     => 'CDM', 
                'address'          => 'José Artigas N° 1628',
                'observation'      => 'Centro Poblado: San Martin.',
                #'president'        => 'HAYDEE EMILIA ESLAVA DE AGUIRRE',
                'resolution_id'    => 50,
                'state_id'         => 1,
                'place_sector_id'  => 30,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
                // Falta chequear csu company
            ],
            [
                'code'             => '068',
                'name'             => 'LA FUERZA DEL PUEBLO',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.4 Lt.14 IV Sector',
                'observation'      => 'Centro Poblado: Wichanzao.',
                #'president'        => 'YENY MARIANELLA QUEZADA CASTILLO DE AMAYA',
                'resolution_id'    => 130,
                'state_id'         => 1,
                'place_sector_id'  => 14,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '075',
                'name'             => 'LAS DALIAS',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.22 Lt.01 AA.HH.',
                'observation'      => 'Centro Poblado: Primavera II.',
                #'president'        => 'MERLI ROCIO ZELADA PALACIOS',
                'resolution_id'    => 194,
                'state_id'         => 1,
                'place_sector_id'  => 12,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '032',
                'name'             => 'LOS ANGELES DE JESUS',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.T Lt.10 AA.HH.',
                'observation'      => 'Centro Poblado: Ampliación Las Palmeras II.',
                #'president'        => 'YOVANA LISBETH VASQUEZ LOYOLA',
                'resolution_id'    => 83,
                'state_id'         => 1,
                'place_sector_id'  => 7,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '246',
                'name'             => 'LOS GERANIOS',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.20 Lt.8',
                'observation'      => 'Centro Poblado: Manuel Seoane.',
                #'president'        => 'ANTONILA BALTAZAR GOMEZ',
                'resolution_id'    => 39,
                'state_id'         => 1,
                'place_sector_id'  => 32,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '022',
                'name'             => 'MADRE DE CRISTO',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.Q Lt.3 AA.HH.',
                'observation'      => 'Centro Poblado: Las Palmeras I.',
                #'president'        => 'ALEYDA GISSELA LINARES AQUITUARI',
                'resolution_id'    => 110,
                'state_id'         => 1,
                'place_sector_id'  => 5,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
                // falta chequear company
            ],
            [
                'code'             => '111',
                'name'             => 'MADRE JOSEFINA POTEL',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.08 Lt.06',
                'observation'      => 'Centro Poblado: Ampliacion nuevo Indoamérica.',
                #'president'        => 'CARLA DAMARIS VILLANUEVA CRUZADO',
                'resolution_id'    => 16,
                'state_id'         => 1,
                'place_sector_id'  => 20,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '045',
                'name'             => 'MADRES TRABAJANDO POR AMPLIACION',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.M Lt.04 AA.HH',
                'observation'      => 'Centro Poblado: Clementina Peralta de Acuña.',
                #'president'        => 'MELISA YENI ZAVALA ASCATE',
                'resolution_id'    => 123,
                'state_id'         => 1,
                'place_sector_id'  => 10,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '258',
                'name'             => 'MANOS SOLIDARIAS',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.C Lt.08 I Sector AA.HH.',
                'observation'      => 'Centro Poblado: Nuevo Jerusalén.',
                #'president'        => 'LUZ ELENA HERAS TASILLA',
                'resolution_id'    => 122,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '274',
                'name'             => 'MARTIN NAMAY',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.G Lt.12 IV Sector',
                'observation'      => 'Centro Poblado: Nuevo Jerusalen.',
                #'president'        => 'DANICA JULLISA MARTINEZ JARA',
                'resolution_id'    => 188,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '034',
                'name'             => 'MUJERES LUCHADORAS',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.F Lt.20 Sector I AA.HH.',
                'observation'      => 'Centro Poblado: Las Palmeras.',
                #'president'        => 'ANALIA DEL CARMEN RIMAYCUNA AGURTO',
                'resolution_id'    => 144,
                'state_id'         => 1,
                'place_sector_id'  => 3,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '302',
                'name'             => 'MUJERES LUCHANDO POR UN FUTURO MEJOR',
                'company_name'     => 'CDM', 
                'address'          => 'Av. Chancay N° 400',
                'observation'      => 'Centro Poblado: Santa Verónica.',
                #'president'        => 'ASHLLY OBET JAIME GARCIA',
                'resolution_id'    => 46,
                'state_id'         => 1,
                'place_sector_id'  => 34,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '295',
                'name'             => 'NIÑO MANUELITO',
                'company_name'     => 'CDM', 
                'address'          => 'Av. Cahuide N° 230',
                'observation'      => 'Centro Poblado: Santa Verónica.',
                #'president'        => 'ASTRI KAROLINA CASTILLO PAIMA',
                'resolution_id'    => 1,
                'state_id'         => 1,
                'place_sector_id'  => 34,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '256',
                'name'             => 'NIÑOS DEL TRIUNFO',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.A Lt.25 III Etapa',
                'observation'      => 'Centro Poblado: Los Laureles',
                #'president'        => 'INDIRA JHOSALIN FERNANDEZ ARTEAGA',
                'resolution_id'    => 104,
                'state_id'         => 1,
                'place_sector_id'  => 40,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
                // faltan los campos company_name
            ],
            [
                'code'             => '170',
                'name'             => 'NUESTRA SEÑORA AUXILIO DE LOS CRISTIANOS',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.29 Lt.5',
                'observation'      => 'Centro Poblado: Fraternidad.',
                #'president'        => 'RUBI ESMELDA ARTEAGA LEON',
                'resolution_id'    => 162,
                'state_id'         => 1,
                'place_sector_id'  => 25,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '078',
                'name'             => 'NUEVO EDEN',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.01 Lt.03 Los Cipreces AA.HH.',
                'observation'      => 'Centro Poblado: Primavera II.',
                #'president'        => 'KATHERINE KARINA GUTIERREZ CHAVEZ',
                'resolution_id'    => 57,
                'state_id'         => 1,
                'place_sector_id'  => 12,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '253',
                'name'             => 'NUEVO PARAISO',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.A10 Lt.10',
                'observation'      => 'Centro Poblado: Virgen de la Puerta.',
                #'president'        => 'FIORELA VIRGINIA CARRANZA MALQUI',
                'resolution_id'    => 113,
                'state_id'         => 1,
                'place_sector_id'  => 33,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '278',
                'name'             => 'NVO. JERUSALEN LA ALEGRIA DE LOS NIÑOS',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.Q Lt.22 IV Sector AA.HH.',
                'observation'      => 'Centro Poblado: Nuevo Jerusalén.',
                #'president'        => 'MONICA GLADIS FLORIAN CRUZ',
                'resolution_id'    => 133,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '271',
                'name'             => 'ROSITA DE AMOR',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.H Lt.36 III Etapa',
                'observation'      => 'Centro Poblado: Nuevo Jerusalén.',
                #'president'        => 'ALEXANDRA ANALI ORTIZ TUMBAJULCA',
                'resolution_id'    => 174,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '350',
                'name'             => 'SAN JOSE',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.F Lt.40',
                'observation'      => 'Centro Poblado: Villa Hermosa.',
                #'president'        => 'ROSA GOMEZ ESPINOZA',
                'resolution_id'    => 175,
                'state_id'         => 1,
                'place_sector_id'  => 37,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '005',
                'name'             => 'SANTA RITA DE CASIA',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.7 LT.12',
                'observation'      => 'Centro Poblado: Nuevo Horizonte.',
                #'president'        => 'GIOVANNA ELIZABETH PAREDES ESQUIVEL',
                'resolution_id'    => 103,
                'state_id'         => 1,
                'place_sector_id'  => 1,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '230',
                'name'             => 'SANTISIMO SACRAMENTO',
                'company_name'     => 'CDM', 
                'address'          => 'Blanco Encalada N° 945',
                'observation'      => 'Centro Poblado: Central. ',
                #'president'        => 'YOBANA ISABEL ROBLES SALAS',
                'resolution_id'    => 102,
                'state_id'         => 1,
                'place_sector_id'  => 29,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '268',
                'name'             => 'SEMBRANDO ESPERANZA',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.B Lt.15 Sector 3 "B" AA.HH.',
                'observation'      => 'Centro Poblado: Nuevo Jerusalén.',
                #'president'        => 'FLOR ESTELA SEGURA CRUZADO',
                'resolution_id'    => 107,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
                // chequear el company
            ],
            [
                'code'             => '019',
                'name'             => 'SOL Y ARENA DE LAS PALMERITAS',
                'company_name'     => 'CDM', 
                'address'          => 'Ampliación I Mz.B Lt.30 calle Los Laureles',
                'observation'      => 'Centro Poblado: Las Palmeras.',
                #'president'        => 'DINA BISABE RABANAL VILLALOBOS',
                'resolution_id'    => 72,
                'state_id'         => 1,
                'place_sector_id'  => 3,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '388',
                'name'             => 'SUPERMAMAS N° 1',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.L13 Lt.2',
                'observation'      => 'Centro Poblado: Virgen del Socorro.',
                #'president'        => 'LIGNE JESUS BLAS URQUIZA',
                'resolution_id'    => 147,
                'state_id'         => 1,
                'place_sector_id'  => 39,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
                // chequear el company
            ],
            [
                'code'             => '385',
                'name'             => 'TANIA SOLEDAD BACA ROMERO II',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.P13 Lt.12B',
                'observation'      => 'Centro Poblado: Virgen del Socorro.',
                #'president'        => 'PATRICIA MARISOL CARRANZA LINARES',
                'resolution_id'    => 87,
                'state_id'         => 1,
                'place_sector_id'  => 39,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '118',
                'name'             => 'UNIDAS EN UN SOLO CORAZÓN',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.8 Lt.13 Los Rosales',
                'observation'      => 'Centro Poblado: Los Rosales.',
                #'president'        => 'YARITZA ARACELY REYES RAMOS',
                'resolution_id'    => 94,
                'state_id'         => 1,
                'place_sector_id'  => 24,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '028',
                'name'             => 'UNIDAS POR LA FAMILIA',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.C Lt.08',
                'observation'      => 'Centro Poblado: Ampliac. Las Palmeras.',
                #'president'        => 'ANGELICA ADRIANA LAYZA LAVADO',
                'resolution_id'    => 158,
                'state_id'         => 1,
                'place_sector_id'  => 6,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '305',
                'name'             => 'VICTOR RAUL',
                'company_name'     => 'OSB', 
                'address'          => 'Marco del Pont N° 2065',
                'observation'      => 'Centro Poblado: Santa Veronica.',
                #'president'        => 'ANDREA ROSARIO ISIQUE VERA',
                'resolution_id'    => 167,
                'state_id'         => 1,
                'place_sector_id'  => 34,
                'type_premises_id' => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'code'             => '090',
                'name'             => 'VIRGEN DE GUADALUPE',
                'company_name'     => 'OSB', 
                'address'          => 'MZ.2 LT.12',
                'observation'      => 'Centro Poblado: Ramiro Priale.',
                #'president'        => 'MARIA TEOFILA SALAZAR SANDOVAL',
                'resolution_id'    => 92,
                'state_id'         => 1,
                'place_sector_id'  => 18,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
                // chequear el company
            ],
            [
                'code'             => '059',
                'name'             => 'VIRGEN DE LA PUERTA',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.25 Lt.5A III Sector',
                'observation'      => 'Centro Poblado: Nuevo Jerusalén.',
                #'president'        => 'LISETT DEL RUBY RUBIO DIESTRA',
                'resolution_id'    => 56,
                'state_id'         => 1,
                'place_sector_id'  => 31,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
                // chequear el company
            ],
            [
                'code'             => '037',
                'name'             => 'WILMER SANCHEZ',
                'company_name'     => 'CDM', 
                'address'          => 'Mz.5 Lt.4',
                'observation'      => 'Centro Poblado: María Elena Moyano',
                #'president'        => 'ANGELICA ALICIA SANCHEZ PAREDES',
                'resolution_id'    => 21,
                'state_id'         => 1,
                'place_sector_id'  => 9,
                'type_premises_id' => 2,
                'created_at'       => now(),
                'updated_at'       => now(),
                // chequear el company
            ],
        ];

        DB::table('associations')->insert($associations);
    }
}