<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ResolutionSeeder extends Seeder
{
    /**
     * Resoluciones extraídas del Reporte de Estructura de Comités.
     * Vigentes: state_id=1, con fechas de vigencia.
     * Anteriores: state_id=2, sin fechas.
     */
    public function run(): void
    {
        $resolutions = [
            [
                'document'   => '0005-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0008-2024',
                'date_start' => '2024-01-09',
                'date_end'   => '2026-01-09',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0015-2024',
                'date_start' => '2024-01-11',
                'date_end'   => '2026-01-11',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0023-2024',
                'date_start' => '2024-01-15',
                'date_end'   => '2026-01-15',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0024-2024',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0025-2024',
                'date_start' => '2024-01-16',
                'date_end'   => '2026-01-16',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0028-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0035-2024',
                'date_start' => '2024-01-19',
                'date_end'   => '2026-01-19',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0039-2024',
                'date_start' => '2024-01-22',
                'date_end'   => '2026-01-22',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0040-2024',
                'date_start' => '2024-01-22',
                'date_end'   => '2026-01-22',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0041-2024',
                'date_start' => '2024-01-22',
                'date_end'   => '2026-01-22',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0044-2024',
                'date_start' => '2024-01-23',
                'date_end'   => '2026-01-23',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0044-2026',
                'date_start' => '2026-01-16',
                'date_end'   => '2028-01-16',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0045-2024',
                'date_start' => '2024-01-23',
                'date_end'   => '2026-01-23',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0046-2024',
                'date_start' => '2024-01-23',
                'date_end'   => '2026-01-23',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0067-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0082-2026',
                'date_start' => '2026-01-23',
                'date_end'   => '2028-01-23',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0096-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0098-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0126-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0146-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0147-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0148-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0151-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0152-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0154-2025',
                'date_start' => '2025-02-12',
                'date_end'   => '2027-02-12',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0155-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0155-2025',
                'date_start' => '2025-02-12',
                'date_end'   => '2027-02-12',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0156-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0156-2025',
                'date_start' => '2025-02-13',
                'date_end'   => '2027-02-13',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0158-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0159-20222',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0164-2024',
                'date_start' => '2024-03-22',
                'date_end'   => '2026-03-22',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0172-2025',
                'date_start' => '2025-02-18',
                'date_end'   => '2027-02-18',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0173-2024',
                'date_start' => '2024-03-26',
                'date_end'   => '2026-03-26',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0176-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0205-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0206-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0207-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0215-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0215-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0215-2025',
                'date_start' => '2025-02-28',
                'date_end'   => '2027-02-28',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0220-2025',
                'date_start' => '2025-03-03',
                'date_end'   => '2027-03-03',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0240-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0244-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0252-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0257-2025',
                'date_start' => '2025-03-06',
                'date_end'   => '2027-03-06',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0259-2025',
                'date_start' => '2025-03-07',
                'date_end'   => '2027-03-07',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0260-2025',
                'date_start' => '2025-03-07',
                'date_end'   => '2027-03-07',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0283-2025',
                'date_start' => '2025-03-17',
                'date_end'   => '2027-03-17',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0295-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0299-2025',
                'date_start' => '2025-03-24',
                'date_end'   => '2027-03-24',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0304-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0310-2021-',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0312-2024',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0316-2025',
                'date_start' => '2025-03-27',
                'date_end'   => '2027-03-27',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0317-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0317-2025',
                'date_start' => '2025-03-28',
                'date_end'   => '2027-03-28',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0319-2024',
                'date_start' => '2024-05-20',
                'date_end'   => '2026-05-20',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0334-2025',
                'date_start' => '2025-04-04',
                'date_end'   => '2027-04-04',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0356-2024',
                'date_start' => '2024-05-28',
                'date_end'   => '2026-05-28',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0363-2024',
                'date_start' => '2024-05-30',
                'date_end'   => '2026-05-30',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0416-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0444-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0461-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0472-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0485-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0505-2024',
                'date_start' => '2024-06-21',
                'date_end'   => '2026-06-21',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0510-2024',
                'date_start' => '2024-06-24',
                'date_end'   => '2026-06-24',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0514-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0525-2025',
                'date_start' => '2025-05-22',
                'date_end'   => '2027-05-22',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0535-2024',
                'date_start' => '2024-06-28',
                'date_end'   => '2026-06-28',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0536-2024',
                'date_start' => '2024-06-28',
                'date_end'   => '2026-06-28',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0541-2025',
                'date_start' => '2025-05-27',
                'date_end'   => '2027-05-27',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0543-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0551-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0559-2025',
                'date_start' => '2025-05-30',
                'date_end'   => '2027-05-30',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0587-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0601-2024',
                'date_start' => '2024-07-10',
                'date_end'   => '2026-07-10',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0605-2025',
                'date_start' => '2025-06-12',
                'date_end'   => '2027-06-12',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0612-2024',
                'date_start' => '2024-07-12',
                'date_end'   => '2026-07-12',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0630-2024',
                'date_start' => '2024-07-19',
                'date_end'   => '2026-07-19',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0671-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0689-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0690-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0691-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0744-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0745-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0770-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0774-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0785-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0790-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0793-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0796-2024',
                'date_start' => '2024-08-29',
                'date_end'   => '2026-08-29',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0800-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0801-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0825-2025',
                'date_start' => '2025-07-22',
                'date_end'   => '2027-07-22',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0863-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0890-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0891-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0907-2025',
                'date_start' => '2025-08-20',
                'date_end'   => '2027-08-20',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0920-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0921-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0932-2025',
                'date_start' => '2025-08-27',
                'date_end'   => '2027-08-27',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0948-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0956-2025',
                'date_start' => '2025-09-05',
                'date_end'   => '2027-09-05',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0993-2025',
                'date_start' => '2025-09-17',
                'date_end'   => '2027-09-17',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '0997-2024',
                'date_start' => '2024-10-10',
                'date_end'   => '2026-10-10',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1000-2025',
                'date_start' => '2025-09-19',
                'date_end'   => '2027-09-19',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1001-2025',
                'date_start' => '2025-09-19',
                'date_end'   => '2027-09-19',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1014-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1019-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1048-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1060-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1062-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1068-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1081-2024',
                'date_start' => '2024-11-06',
                'date_end'   => '2026-11-06',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1083-2025',
                'date_start' => '2025-10-17',
                'date_end'   => '2027-10-17',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1084-2025',
                'date_start' => '2025-10-17',
                'date_end'   => '2027-10-17',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1098-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1101-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1104-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1105-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1118-2024',
                'date_start' => '2024-11-08',
                'date_end'   => '2026-11-08',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1137-2024',
                'date_start' => '2024-11-13',
                'date_end'   => '2026-11-13',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1148-2025',
                'date_start' => '2025-10-28',
                'date_end'   => '2027-10-28',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1149-2025',
                'date_start' => '2025-10-28',
                'date_end'   => '2027-10-28',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1162-2024',
                'date_start' => '2024-11-20',
                'date_end'   => '2026-11-20',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1163-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1165-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1169-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1170-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1173-2024',
                'date_start' => '2024-11-22',
                'date_end'   => '2026-11-22',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1174-2024',
                'date_start' => '2024-11-22',
                'date_end'   => '2026-11-22',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1179-2025',
                'date_start' => '2025-11-07',
                'date_end'   => '2027-11-07',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1180-2025',
                'date_start' => '2025-11-07',
                'date_end'   => '2027-11-07',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1181-2025',
                'date_start' => '2025-11-07',
                'date_end'   => '2027-11-07',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1206-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1208-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1209-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1212-2019',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1215-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1217-2025',
                'date_start' => '2025-11-17',
                'date_end'   => '2027-11-17',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1232-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1233-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1233-2025',
                'date_start' => '2025-11-20',
                'date_end'   => '2027-11-20',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1235-2025',
                'date_start' => '2025-11-20',
                'date_end'   => '2027-11-20',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1240-2024',
                'date_start' => '2024-12-02',
                'date_end'   => '2026-12-02',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1243-2024',
                'date_start' => '2024-12-02',
                'date_end'   => '2026-12-02',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1244-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1245-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1249-2024',
                'date_start' => '2024-12-04',
                'date_end'   => '2026-12-04',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1256-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1259-2020',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1264-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1288-2024',
                'date_start' => '2024-12-13',
                'date_end'   => '2026-12-13',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1312-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1322-2024',
                'date_start' => '2024-12-23',
                'date_end'   => '2026-12-23',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1332-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1333-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1335-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1340-2019',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1340-2024',
                'date_start' => '2024-12-31',
                'date_end'   => '2026-12-31',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1343-2024',
                'date_start' => '2024-12-31',
                'date_end'   => '2026-12-31',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1345-2025',
                'date_start' => '2025-12-23',
                'date_end'   => '2027-12-23',
                'state_id'   => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1355-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1365-2019',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1382-2019',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1385-2019',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1399-2019',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1414-2019',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1421-2019',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1432-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1443-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1474-2019',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1503-2019',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1511-2019',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1514-2019',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1546-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1586-2019',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1595-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1616-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1697-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1704-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1704-2023',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1712-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1713-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1714-2022',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1732-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1733-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1734-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1735-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1747-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1770-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1771-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1775-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document'   => '1812-2021',
                'date_start' => '',
                'date_end'   => '',
                'state_id'   => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('resolutions')->insert($resolutions);
    }
}